const TIME_FRAME_MS = 100;

const UNIT_DEFAULT_SPEED = 5;
const UNIT_DEFAULT_HEALTH = 100;
const UNIT_DEFAULT_HEALTH_DECAY = 0.5;
const UNIT_DEFAULT_VELOCITY_LOSS = 0.98;
const UNIT_DEFAULT_VISION_SQUARE_LENGTH = 20;
const UNIT_DEFAULT_VISION_SQUARE_TOTAL_NUMBER = 20;
const UNIT_DEFAULT_VISION_SQUARE_NUMBER_DEEP = 4;
const UNIT_DEFAULT_VISION_HALF_SIDE_LENGTH = UNIT_DEFAULT_VISION_SQUARE_TOTAL_NUMBER * UNIT_DEFAULT_VISION_SQUARE_LENGTH / (UNIT_DEFAULT_VISION_SQUARE_NUMBER_DEEP * 2) 

const TIMER_UNIT_ACT = 100;
const TIMER_FRUIT_SPAWN = 1000;

const SEED_STR = 'TEST';
