const TIME_FRAME_MS = 100;

const UNIT_DEFAULT_SPEED = 5;
const UNIT_DEFAULT_HEALTH = 100;
const UNIT_DEFAULT_HEALTH_DECAY = 2;

const TIMER_UNIT_ACT = 100;
const TIMER_FRUIT_SPAWN = 1000;

const SEED_STR = 'TEST';
